vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL git@github.com:KinderLi/dtssdk-release.git
    REF 78bc22a4bb465f1f4eb59d522cb311e2a8768b4a # 3.2.6.7
)

file(INSTALL ${SOURCE_PATH}/${TARGET_TRIPLET}/debug DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/${TARGET_TRIPLET}/include DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/${TARGET_TRIPLET}/lib DESTINATION ${CURRENT_PACKAGES_DIR})
file(INSTALL ${SOURCE_PATH}/${TARGET_TRIPLET}/share DESTINATION ${CURRENT_PACKAGES_DIR})

vcpkg_fixup_cmake_targets(CONFIG_PATH share/dtssdk)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")

file(INSTALL ${SOURCE_PATH}/copyright DESTINATION ${CURRENT_PACKAGES_DIR}/share/dtssdk RENAME copyright)
